#Recordar asiganr todo como variables de entorno
version: '3.3'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data